"""
Data models for the Civilization Database API
"""

from .civilization_schema import (
    CivilizationMetadata,
    CivilizationResponse,
    CivilizationList,
    CivilizationRelationship,
    CivilizationRelationshipList,
    CivilizationHistoryEvent,
    CivilizationHistoryList,
    # Enums
    SettlementPattern,
    PrimaryTerrain,
    PopulationDensity,
    ArchitectureStyle,
    GovernmentType,
    LeadershipSelection,
    CentralizationLevel,
    LegalSystem,
    PrimaryEconomy,
    TradeOrientation,
    CurrencyType,
    PropertyRights,
    SocialStratification,
    GenderRoles,
    FamilyStructure,
    AgeHierarchy,
    PrimaryReligion,
    ReligiousInfluence,
    ArtFocus,
    CulturalValues,
    EducationSystem,
    LiteracyRate,
    KnowledgeBasis,
    TechnologyLevel,
    MilitaryStructure,
    WarfareApproach,
    PrimaryWeapons,
    LanguageComplexity,
    WritingSystem,
    CommunicationMethods,
    ResourceUse,
    AgricultureType,
    EnergySources,
    PopulationSize,
    LifeExpectancy,
    TechnologicalAdoption,
    ExternalRelations,
    ChangeRate,
)

__version__ = "1.0.0"
__author__ = "Your Name"
__description__ = "API for storing, retrieving, and analyzing civilization data"

__all__ = [
    "CivilizationMetadata",
    "CivilizationResponse",
    "CivilizationList",
    "CivilizationRelationship",
    "CivilizationRelationshipList",
    "CivilizationHistoryEvent",
    "CivilizationHistoryList",
    # Enums
    "SettlementPattern",
    "PrimaryTerrain",
    "PopulationDensity",
    "ArchitectureStyle",
    "GovernmentType",
    "LeadershipSelection",
    "CentralizationLevel",
    "LegalSystem",
    "PrimaryEconomy",
    "TradeOrientation",
    "CurrencyType",
    "PropertyRights",
    "SocialStratification",
    "GenderRoles",
    "FamilyStructure",
    "AgeHierarchy",
    "PrimaryReligion",
    "ReligiousInfluence",
    "ArtFocus",
    "CulturalValues",
    "EducationSystem",
    "LiteracyRate",
    "KnowledgeBasis",
    "TechnologyLevel",
    "MilitaryStructure",
    "WarfareApproach",
    "PrimaryWeapons",
    "LanguageComplexity",
    "WritingSystem",
    "CommunicationMethods",
    "ResourceUse",
    "AgricultureType",
    "EnergySources",
    "PopulationSize",
    "LifeExpectancy",
    "TechnologicalAdoption",
    "ExternalRelations",
    "ChangeRate",
]
