# docker-compose.yml (with volume mounts for hybrid approach)
version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - model_storage:/app/storage  # Persistent volume for file storage
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - DB_NAME=model_database
      - STORAGE_DIR=/app/storage
    depends_on:
      - mongodb
    networks:
      - model-api-network

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - model-api-network

networks:
  model-api-network:
    driver: bridge

volumes:
  mongodb_data:  # For MongoDB data
  model_storage:  # For 3D model and texture files